export enum CategoriaServicoEnum {
  PINTURA = 'PINTURA',
  ELETRICA = 'ELETRICA',
  HIDRAULICA = 'HIDRAULICA',
  ALVENARIA = 'ALVENARIA',
  ACABAMENTO = 'ACABAMENTO',
  MARCENARIA = 'MARCENARIA',
  GESSO = 'GESSO',
  ESQUADRIAS = 'ESQUADRIAS',
  OUTROS = 'OUTROS',
}
